apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks-web-app-deployment 
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: aks-web-app
  template: 
    metadata:
      labels: 
        app: aks-web-app
    spec: 
      containers:
      - name: aks-web-app-container
        image: nginx 
        ports: 
        - containerPort: 80
          name: http 
        resources:
          requests: 
            cpu: 100m
            memory: 128Mi
          limits: 
            cpu: 250m
            memory: 512Mi